Repository unb-mds/Mds-ArenaPesadelo, pull requests merged in 2024-04, with the labels that each got.

#13 docs: Template para as ATAS
  docs/ATAS/ATA_03_04.pdf
  docs/ATAS/ATA_07_04.pdf
  docs/ATAS/ATA_XX_XX (1).pdf
Labels: documentation

#16 docs: Atualização do Readme #15
  README.md
  docs/assets/IMAGEM_PESADELO.png
Labels: documentation

#17 Reade update
  Gitpage/docs/SobreOJogo.md
  Gitpage/docs/index.md
  Gitpage/mkdocs.yml
  Gitpage/site/404.html
  Gitpage/site/SobreOJogo/index.html
  Gitpage/site/assets/images/favicon.png
  Gitpage/site/assets/javascripts/bundle.bd41221c.min.js
  Gitpage/site/assets/javascripts/bundle.bd41221c.min.js.map
  Gitpage/site/assets/javascripts/lunr/min/lunr.ar.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.da.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.de.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.du.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.el.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.es.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.fi.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.fr.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.he.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.hi.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.hu.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.hy.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.it.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.ja.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.jp.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.kn.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.ko.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.multi.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.nl.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.no.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.pt.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.ro.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.ru.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.sa.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.stemmer.support.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.sv.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.ta.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.te.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.th.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.tr.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.vi.min.js
  Gitpage/site/assets/javascripts/lunr/min/lunr.zh.min.js
  Gitpage/site/assets/javascripts/lunr/tinyseg.js
  Gitpage/site/assets/javascripts/lunr/wordcut.js
  Gitpage/site/assets/javascripts/workers/search.b8dbb3d2.min.js
  Gitpage/site/assets/javascripts/workers/search.b8dbb3d2.min.js.map
  Gitpage/site/assets/stylesheets/main.7e359304.min.css
  Gitpage/site/assets/stylesheets/main.7e359304.min.css.map
  Gitpage/site/assets/stylesheets/palette.06af60db.min.css
  Gitpage/site/assets/stylesheets/palette.06af60db.min.css.map
  Gitpage/site/index.html
  Gitpage/site/search/search_index.json
  Gitpage/site/sitemap.xml
  Gitpage/site/sitemap.xml.gz
  README.md
  docs/ATAS/ATA_03_04.pdf
  docs/ATAS/ATA_07_04.pdf
  docs/ATAS/ATA_XX_XX (1).pdf
  docs/BACKLOG.md
  docs/CODE-PATTERNS.md
  docs/assets/IMAGEM_PESADELO.png
Labels: documentation

#19 Pages
  .github/COMMIT_PATTERN.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#25 Feat: Deletando pasta clone
  github/COMMIT_PATTERN.md
  github/ISSUE_TEMPLATE.md
  github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, Gitpage

#26 feat: Alterando detalhes na gitpage #3
  Gitpage/mkdocs.yml
Labels: documentation, Gitpage

#28 Fix: Finalizando front-end para primeira release
  projetos/front-end/src/assets/img/horse.png
  projetos/front-end/src/assets/img/players.png
  projetos/front-end/src/assets/img/switching.png
  projetos/front-end/src/assets/img/time.png
  projetos/front-end/src/clean
  projetos/front-end/src/pages/public/Inicial/index.jsx
  projetos/front-end/src/pages/public/Inicial/styles.js
  projetos/front-end/src/pages/public/User/index.jsx
  projetos/front-end/src/pages/public/User/styles.js
  projetos/front-end/src/routes/index.jsx
Labels: enhancement
